// Word lists for generating memorable passwords
export const adjectives = [
  "happy",
  "sunny",
  "bright",
  "swift",
  "calm",
  "wise",
  "kind",
  "brave",
  "cool",
  "warm",
  "quick",
  "gentle",
  "strong",
  "clever",
  "noble",
  "proud",
  "smooth",
  "fresh",
  "grand",
  "clear",
  "bold",
  "fierce",
  "quiet",
  "loud",
  "soft",
  "hard",
  "light",
  "dark",
  "young",
  "old",
  "new",
  "ancient",
  "modern",
  "classic",
  "simple",
  "complex",
  "easy",
  "tough",
  "sweet",
  "sharp",
  "round",
  "square",
  "tall",
  "short",
  "wide",
  "narrow",
  "deep",
  "shallow",
  "fast",
  "slow",
]

export const nouns = [
  "tiger",
  "eagle",
  "dolphin",
  "lion",
  "bear",
  "wolf",
  "hawk",
  "falcon",
  "phoenix",
  "dragon",
  "mountain",
  "river",
  "ocean",
  "forest",
  "desert",
  "valley",
  "canyon",
  "glacier",
  "volcano",
  "island",
  "thunder",
  "lightning",
  "rainbow",
  "sunrise",
  "sunset",
  "moonlight",
  "starlight",
  "comet",
  "meteor",
  "aurora",
  "crystal",
  "diamond",
  "emerald",
  "sapphire",
  "ruby",
  "pearl",
  "amber",
  "coral",
  "jade",
  "opal",
  "sword",
  "shield",
  "arrow",
  "hammer",
  "lance",
  "axe",
  "crown",
  "throne",
  "castle",
  "tower",
]

export function generateMemorablePassword(): string {
  const adj1 = adjectives[Math.floor(Math.random() * adjectives.length)]
  const adj2 = adjectives[Math.floor(Math.random() * adjectives.length)]
  const noun1 = nouns[Math.floor(Math.random() * nouns.length)]
  const noun2 = nouns[Math.floor(Math.random() * nouns.length)]

  // Capitalize first letter of each word
  const capitalize = (word: string) => word.charAt(0).toUpperCase() + word.slice(1)

  return `${capitalize(adj1)}${capitalize(noun1)}${capitalize(adj2)}${capitalize(noun2)}`
}
